In [1]:
import pandas as pd

In [5]:
data = pd.read_csv('ILOSTAT_.csv')

In [6]:
data

,collection,collection.label,ref_area,ref_area.label,source,source.label,indicator,indicator.label,sex,sex.label,...,obs_value,obs_status,obs_status.label,note_classif,note_classif.label,note_indicator,note_indicator.label,note_source,note_source.label,Unnamed: 30
0,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,52.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
1,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
2,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
3,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
4,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
5,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
6,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
7,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,7.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
8,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
9,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
10,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
11,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,NaN,S,Not significant,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
12,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,27.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
13,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
14,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
15,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
16,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
17,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
18,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
19,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
20,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
21,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
22,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
23,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,NaN,S,Not significant,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
24,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,24.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
25,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
26,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
27,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
28,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
29,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59815,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,167.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59816,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,380.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59817,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59818,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59819,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,3175.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59820,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,19.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59821,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,111.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59822,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,35.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59823,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,32.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59824,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,381.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59825,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,2156.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59826,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,70.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59827,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59828,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,362.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59829,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59830,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59831,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,6266.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59832,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,384.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59833,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,5131.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59834,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,742.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59835,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59836,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,3091.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59837,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,219.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59838,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,2482.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59839,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,380.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59840,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_M,Sex: Male,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59841,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,3175.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59842,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,165.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59843,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,2648.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN
59844,YI,Yearly indicators,ZWE,Zimbabwe,BA:1823,ZWE - LFS - Labour Force Survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_F,Sex: Female,...,362.0,NaN,NaN,NaN,NaN,NaN,NaN,S14:4077_S3:17,Employment definition: Excluding own-use produ...,NaN

In [7]:
data.head(5)

,collection,collection.label,ref_area,ref_area.label,source,source.label,indicator,indicator.label,sex,sex.label,...,obs_value,obs_status,obs_status.label,note_classif,note_classif.label,note_indicator,note_indicator.label,note_source,note_source.label,Unnamed: 30
0,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,52.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
1,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
2,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
3,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN
4,YI,Yearly indicators,ABW,Aruba,BA:829,ABW - LFS - Labour force survey,EMP_TEMP_SEX_OCU_NB,Employment by sex and occupation (thousands),SEX_T,Sex: Total,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,S3:21,Data reference period: October,NaN

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59845 entries, 0 to 59844
Data columns (total 31 columns):
collection              59845 non-null object
collection.label        59845 non-null object
ref_area                59845 non-null object
ref_area.label          59845 non-null object
source                  59845 non-null object
source.label            59845 non-null object
indicator               59845 non-null object
indicator.label         59845 non-null object
sex                     59845 non-null object
sex.label               59845 non-null object
classif1                59845 non-null object
classif1.label          59845 non-null object
classif2                0 non-null float64
classif2.label          0 non-null float64
classif3                0 non-null float64
classif3.label          0 non-null float64
classif4                0 non-null float64
classif4.label          0 non-null float64
classif5                0 non-null float64
classif5.label          0 non-null float64
time                    59845 non-null int64
obs_value               59180 non-null float64
obs_status              6846 non-null object
obs_status.label        6846 non-null object
note_classif            390 non-null object
note_classif.label      390 non-null object
note_indicator          5733 non-null object
note_indicator.label    5733 non-null object
note_source             56635 non-null object
note_source.label       56635 non-null object
Unnamed: 30             0 non-null float64
dtypes: float64(10), int64(1), object(20)
memory usage: 9.6+ MB